# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494f8698cfe3c462adc350c5b01392488b0b1db5bf934c6af86c81b5d2c89bf84467d41a4ad07d81d831a848a80db06ca55d4d1a3dfc48a86a0048622e6d79d0

test:
  secret_key_base: 20be5023404d72383f87b02ce796e130ac72922adc54ffedfcedc1d485273458270b27e7bf88f52a59be021f9381def331d53f506131aa1708b82dfe1ba64cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
