NewsExtract.create(:MediumCategory_id => 4, :title => 'Breve guía  youtuber  para extraterrestres', :content => 'Breve guía  youtuber  para extraterrestres', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => '¿Son culpables los fabricantes por el mal uso de sus productos?', :content => '¿Son culpables los fabricantes por el mal uso de sus productos?', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Los computadores más asombrosos de la feria tecnológica CES', :content => 'Los computadores más asombrosos de la feria tecnológica CES', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Estos son los mejores celulares de la feria tecnológica CES', :content => 'Estos son los mejores celulares de la feria tecnológica CES', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Crónica: así se vive la feria tecnológica más grande del mundo', :content => 'Crónica: así se vive la feria tecnológica más grande del mundo', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Se inaugurará wifi gratis en 11 zonas del país', :content => 'Se inaugurará wifi gratis en 11 zonas del país', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Conozca el portátil que vale casi 30 millones de pesos', :content => 'Conozca el portátil que vale casi 30 millones de pesos', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Diez curiosidades de la feria tecnológica CES 2017 ', :content => 'Diez curiosidades de la feria tecnológica CES 2017 ', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Tecnología para el cuidado personal brilla en la feria CES', :content => 'Tecnología para el cuidado personal brilla en la feria CES', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'App Store bate récord de ventas el primer día de 2017', :content => 'App Store bate récord de ventas el primer día de 2017', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'La estrategia de BMW de usar realidad aumentada para vender carros', :content => 'La estrategia de BMW de usar realidad aumentada para vender carros', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Los mejores televisores presentados en el CES 2017', :content => 'Los mejores televisores presentados en el CES 2017', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'CES 2017: Las tecnológicas hacen sus apuestas en Las Vegas', :content => 'CES 2017: Las tecnológicas hacen sus apuestas en Las Vegas', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => '¿Una ciudad inteligente en el mar? Este  gadget  quiere lograrlo', :content => '¿Una ciudad inteligente en el mar? Este  gadget  quiere lograrlo', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Los operadores que más ganaron usuarios en el tercer trimestre de 2016', :content => 'Los operadores que más ganaron usuarios en el tercer trimestre de 2016', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => '¿Problemas para parquear?, este carro inteligente se estaciona solo', :content => '¿Problemas para parquear?, este carro inteligente se estaciona solo', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Vea acá lo mejor de Tecnósfera TV de la semana', :content => 'Vea acá lo mejor de Tecnósfera TV de la semana', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Vea acá lo mejor de Tecnósfera TV de la semana', :content => 'Vea acá lo mejor de Tecnósfera TV de la semana', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Conozca la  app  que quiere mejorar la experiencia de salir a comer', :content => 'Conozca la  app  que quiere mejorar la experiencia de salir a comer', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'En Bogotá se llevará a cabo un torneo nacional de Pokémon', :content => 'En Bogotá se llevará a cabo un torneo nacional de Pokémon', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Niños pasan entre 5 y 10 horas a la semana en internet', :content => 'Niños pasan entre 5 y 10 horas a la semana en internet', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Internet móvil crecerá 50 % en próximos 4 años en América Latina', :content => 'Internet móvil crecerá 50 % en próximos 4 años en América Latina', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Terrorismo en la red: ¿de la alarma al sensacionalismo?', :content => 'Terrorismo en la red: ¿de la alarma al sensacionalismo?', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Facebook le pagó 10.000 dólares a un niño de 10 años', :content => 'Facebook le pagó 10.000 dólares a un niño de 10 años', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Hangout: ¿Llegó o no el hombre a la Luna?', :content => 'Hangout: ¿Llegó o no el hombre a la Luna?', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Hangout con Jackson Galaxy, el encantador de gatos', :content => 'Hangout con Jackson Galaxy, el encantador de gatos', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Conozca cómo aplicar a becas de maestría en el Reino Unido', :content => 'Conozca cómo aplicar a becas de maestría en el Reino Unido', :url => '/')
NewsExtract.create(:MediumCategory_id => 4, :title => 'Silvestre Dangond habló sobre su nueva canción con Nicky Jam', :content => 'Silvestre Dangond habló sobre su nueva canción con Nicky Jam', :url => '/')
